[tool.bumpversion]
current_version = "0.2.1"

parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(?:-(?P<rc_l>rc)(?P<rc>0|[1-9]\\d*))?"

serialize = ["{major}.{minor}.{patch}-{rc_l}{rc}", "{major}.{minor}.{patch}"]
commit = false
tag = false

[tool.bumpversion.parts.minor]
optional = false

[tool.bumpversion.parts.rc_l]
values = ["rc"]

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'
